### ISSUE TITLE
RTSP server "Value does not fall within the expected range. (Parameter 'asyncResult"

### ISSUE THREAD

**Issue by impact81** [juliusfriedman/net7mma_core#13] opened 2023-03-17 01:35 UTC
Im lost on how to fix this: 
"Value does not fall within the expected range. (Parameter 'asyncResult')
    at System.Threading.Tasks.TaskToApm.ThrowArgumentException(IAsyncResult asyncResult)
   at System.Threading.Tasks.TaskToApm.End[TResult](IAsyncResult asyncResult)
   at Media.Rtsp.RtspServer.ProcessAccept(IAsyncResult ar) in \net7mma_core-master\RtspServer\RtspServer.cs:line 1820"

RTSP server starts fine, but as soon as i try to connect using VLC it gives this error. 

I used the original MMA years back with great success, but now i am lost on how to start a simple server.

**Comment by juliusfriedman** [comment] 2023-03-25 20:33
I will check into this when time permits. Thanks for the report.

It should be the same code to start a server for now.

I have been meaning to update some of the server code for .net core and it looks like I might have to do that sooner than I thought.

**Comment by juliusfriedman** [comment] 2023-03-26 00:02
I can confirm this is something with Task wrapping of the IAsyncResult, Its a lot of machinery and I can switch to using the SocketAsyncEventArgs in the server pretty easily Me thinks. I will get the source updated asap.

**Comment by juliusfriedman** [comment] 2023-03-26 00:03
I just pushed up the source and tested it with the Drawing package, it seems to work okay now. Please let me know if you have any other issues! Thanks again for the report!

**Comment by juliusfriedman** [comment] 2023-03-26 14:15
I will close this issue as the server is seemingly working properly in the latest code, if you run into anything else please feel free to create another issue! Thanks again for your help!

**Closed as completed by juliusfriedman** 2023-03-26 14:15 UTC
